PIPRES-6/added price rule logic to get old price for recurring orders…
mollie/PrestaShop1.7 pull request #669
Opened 2023-02-20 14:04 UTC by margud

… and added text for faq

2023-02-21 13:53 UTC, margud commented on subscription/Controller/Symfony/SubscriptionFAQController.php
> +        return $this->render('@Modules/mollie/views/templates/admin/Subscription/subscriptions-faq.html.twig',
Text will be changed by mollie team, now its just the main points from. So dont comment text issues but other part can be reviewed

2023-02-24 08:41 UTC, mandan2 requested changes
Check out if something about specific price could be improved.

2023-02-24 08:41 UTC, mandan2 commented on controllers/admin/AdminMollieSubscriptionFAQController.php
> + * This controller is only used to create tab and redirect to SubscriptionSettingsController
Uhhhh so `AdminMollieSubscriptionFAQParentController` controller has redirect and this one doesn't. Probably forgot to change this here?

2023-02-24 08:41 UTC, mandan2 commented on subscription/Controller/Symfony/SubscriptionFAQController.php
> +                'cartRUleTitle' => $this->module->l('Cart rules', self::FILE_NAME),
Ru*

2023-02-24 08:41 UTC, mandan2 commented on subscription/Handler/RecurringOrderHandler.php
> +        /** @var Cart $newCart */
Check if 'cart' index actually exists in array and if it's actually Cart.

2023-02-24 08:41 UTC, mandan2 commented on subscription/Handler/RecurringOrderHandler.php
> +        $recurringOrder = new MolRecurringOrder($recurringOrderId);
Why you don't use doctrine if other parts are written with symfony?

2023-02-24 08:41 UTC, mandan2 commented on subscription/Handler/RecurringOrderHandler.php
> +        $specificPrice = new SpecificPrice();
Is this "specific price" method used in admin orders too? In admin order you can just change product price for specific cart and no data is inserted/deleted additionally for product I think. Not saying your approach is bad or something, but maybe there is a better way.

2023-02-24 08:41 UTC, mandan2 commented on views/templates/admin/Subscription/subscriptions-faq.html.twig
> +          <i class="material-icons">info_outline</i> {{ subscriptionCreationTittle }}
why is this string not translated? `info_outline`

2023-02-24 08:41 UTC, mandan2 commented on views/templates/admin/Subscription/subscriptions-faq.html.twig
> +  </div>  <div class="row">
lol

2023-02-27 07:30 UTC, margud commented on views/templates/admin/Subscription/subscriptions-faq.html.twig
> +          <i class="material-icons">info_outline</i> {{ subscriptionCreationTittle }}
this is not string this is icon

2023-02-27 07:53 UTC, margud commented on subscription/Handler/RecurringOrderHandler.php
> +        /** @var Cart $newCart */
it is returned from duplicate function, there is check if success is true, and if its true then it will always be cart here. So i dont think we need to add more validations. If for some reason this is not the case then it would be breaking change from prestashop side.

2023-02-27 08:07 UTC, margud commented on subscription/Handler/RecurringOrderHandler.php
> +        $specificPrice = new SpecificPrice();
yes, in admin order page it also create specific price and then deletes it. 
![image](https://user-images.githubusercontent.com/51944825/221508017-9272f636-d860-4f1c-850e-d8d3a7357c40.png)

2023-02-27 08:26 UTC, mandan2 approved these changes

2023-02-27 08:28 UTC, merged